memodir = "$HOME/memo"
editor = "vim"
column = 35
selectcmd = "fzf"
grepcmd = "ag ${PATTERN} ${DIR}"
assetsdir = "."
pluginsdir = "$HOME/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
