language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - make dotfiles
  - make docs
after_success:
  - openssl aes-256-cbc -K $encrypted_f6f8630853eb_key -iv $encrypted_f6f8630853eb_iv -in travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.name "humangas"
  - git config --global user.email "humangas.net@gmail.com"
  - git remote set-url origin git@github.com:humangas/dotfiles.git
  - git checkout master
  - git add dotfiles
  - git commit -m "Updated dotfiles by Travis CI (BUILD $TRAVIS_BUILD_NUMBER:$TRAVIS_BUILD_ID)"
  - git add docs
  - git commit -m "Updated docs by Travis CI (BUILD $TRAVIS_BUILD_NUMBER:$TRAVIS_BUILD_ID)"
  - git push origin master
notifications:
  slack:
    secure: R+MwsM47I0neBiC6/j2PFi6BmZ7fhm71UaHpvF35EohpSZARAV6INh9HID6IHB6yLsonnw5fmd897woq1pDZZCeZE/WyOyp0xjOr1xyTaMF7cGf7krkSXh0J9pMZh3g115DEv+GQJpCeBUpmB12/ImFqb606hBH/KcJpNu88n0CXhUQt0ja51IWsfc80Ne1Gp6FUaoGsz17PYaKr7IJqjIuEE+pI9dHhBBtY2YZVYSBcmjVXqDGdFO2OeWzIvr3MonRpTjbtfc/+/WzQIDGjnwsX7WSCTSivIadQ6EjbqhPsQpqDPcYow0LkbeegUfeFSGd7KA8Xyz9G90itpfVtpEILNyUMZWZKEgZDvB2tgSs9Xd9kwmwGrLyKWxWaDjq1IHoBytP9rUsN8CiVV3kZdpTbtlSQyZgOU8i5G0lUcW/P0c6Ujjon7yEsdOBjXDKrLjjSCk6ZshlclDWFaIE2fuTtLR58GAEAJJQYWCKCVk2UcxJD1gOF1Hxx5gDnXM+LaEJJbMo8pMjBuBLjCr5/oIU+S35HnEEOa3bs56U9xdE0GLA6BQdAu4ershFZV5LfWKur/+UBMJQW3vhhOFG9rDWx7CYaOwvSp9tgSAy5uf+yxZ6DzSFrsFcv/NXmT0M8pjl+vmLqRgSNqQB5AGvIvTyj8EwweObdN7EHfk+Gxu4=
