language: python
python:
    - 3.6
install: 
    - pip install -r requirements.txt
script:
    - make dotfiles
    - make docs
after_success: 
    - openssl aes-256-cbc -K $encrypted_f6f8630853eb_key -iv $encrypted_f6f8630853eb_iv -in travis.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git config --global user.name "humangas"
    - git config --global user.email "humangas.net@gmail.com"
    - git clone git@github.com:humangas/dotfiles.git
    - cd dotfiles
    - make dotfiles
    - git add -A
    - git commit -m "Updated dotfiles by Travis CI (BUILD NUMBER:$TRAVIS_BUILD_NUMBER, ID:$TRAVIS_BUILD_ID)"
    - make docs
    - git add -A
    - git commit -m "Updated docs by Travis CI (BUILD NUMBER:$TRAVIS_BUILD_NUMBER, ID:$TRAVIS_BUILD_ID)"
    - git push origin master
