site_name: humangas's dotfiles
site_url: https://humangas.github.io/dotfiles/
repo_url: https://github.com/humangas/dotfiles/
repo_name: GitHub
site_description: humangas's macOS setup tool and dotfiles
site_author: humangas
copyright: 2017 humangas
google_analytics: ['UA-43176477-6', 'auto']
theme:
  name: 'material'
  language: 'ja'
docs_dir: '_docs'
site_dir: 'docs'
extra:
  search:
    language: 'jp'
